---
- name: Validate
  ansible.builtin.include_tasks: validate.yml

- name: Install Windows roles/features and PowerShell DSC
  ansible.builtin.import_tasks: install.yml

- name: Configure DHCP Server
  ansible.builtin.import_tasks: configure.yml
