---
- name: Configure DHCP scope
  ansible.windows.win_dsc:
    resource_name: xDhcpServerScope
    Ensure: "{{ _dhcp_scope.ensure | default('Present') }}"
    ScopeId: "{{ _dhcp_scope.id }}"
    IPStartRange: "{{ _dhcp_scope.ip_start }}"
    IPEndRange: "{{ _dhcp_scope.ip_end }}"
    Name: "{{ _dhcp_scope.name }}"
    SubnetMask: "{{ _dhcp_scope.subnet_mask }}"
    LeaseDuration: "{{ _dhcp_scope.lease_duration }}"
    AddressFamily: IPv4
    State: "{{ _dhcp_scope.state | default('Active') }}"

- name: Configure DHCP scope options
  loop: "{{ _dhcp_scope.options | default([]) }}"
  ansible.windows.win_dsc:
    resource_name: DhcpScopeOptionValue
    ScopeId: "{{ _dhcp_scope.id }}"
    OptionId: "{{ item.id }}"
    Value: "{{ item.value }}"
    VendorClass: "{{ item.vendor_class | default('') }}"
    UserClass: "{{ item.user_class | default('') }}"
    AddressFamily: IPv4
    Ensure: "{{ item.ensure | default('Present') }}"
