---
galaxy_info:
    author: Jim Tarpley
    namespace: trippsc2
    role_name: install_psgallery
    description: This role installs the PSGallery repository for PowerShell modules on Windows machines.
    license: MIT

    min_ansible_version: '2.15'

    platforms:
      - name: Windows
        versions:
          - '2019'
          - '2022'

collections:
  - ansible.windows
  - community.windows

dependencies: []
