---
namespace: trippsc2
name: windows
version: 1.0.1
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains general purpose Windows modules and roles.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.windows: '>=1.0.0'
  community.windows: '>=1.11.0'

repository: https://github.com/trippsc2/ansible-collection-windows.git

build_ignore:
  - .gitignore
