---
- name: Converge
  hosts:
    - subjects
  gather_facts: false
  tasks:
    - name: Ensure NuGet package provider is installed at the required version
      trippsc2.windows.win_package_provider:
        name: NuGet
        min_version: '2.8.5.201'
