---
- name: Converge
  hosts:
    - subjects
  gather_facts: false
  tasks:
    - name: Add boot image to WDS
      trippsc2.windows.wds_boot_image:
        image_name: boot.wim
        path: C:\Windows\temp\boot.wim
        description: Test Boot Image
        display_order: 1
        state: present

    - name: Remove boot image from WDS
      trippsc2.windows.wds_boot_image:
        image_name: To Be Removed
        state: absent
