---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare member server
  hosts:
    - windows_domain_members
  gather_facts: false
  roles:
    - role: trippsc2.ad.testing_win_member

- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Copy ISO to temp folder
      ansible.windows.win_get_url:
        url: https://software-static.download.prss.microsoft.com/dbazure/988969d5-f34g-4e03-ac9d-1f9786c66749/17763.3650.221105-1748.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso
        dest: C:\Windows\temp\win.iso
    
    - name: Mount ISO
      community.windows.win_disk_image:
        image_path: C:\Windows\temp\win.iso
        state: present
      register: _iso_mount

    - name: Copy boot.wim to temp folder
      ansible.windows.win_copy:
        src: "{{ _iso_mount.mount_paths[0] }}sources\\boot.wim"
        dest: C:\Windows\temp\boot.wim
        remote_src: true

    - name: Install Windows Deployment Services feature
      ansible.windows.win_feature:
        name:
          - WDS
        include_management_tools: true
        state: present

    - name: Initialize WDS
      trippsc2.windows.wds_initialize:
        remote_install_path: C:\RemoteInstall
        state: initialized

    - name: Add boot image to WDS
      trippsc2.windows.wds_boot_image:
        image_name: To Be Removed
        path: C:\Windows\temp\boot.wim
        state: present
