---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare member server
  hosts:
    - windows_domain_members
  gather_facts: false
  roles:
    - role: trippsc2.ad.testing_win_member

- name: Prepare DNS
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.authorize_dhcp_server
