---
- name: Initialize WDS
  throttle: 1
  ansible.windows.win_dsc:
    resource_name: WdsInitialize
    IsSingleInstance: 'Yes'
    Path: "{{ wds_path }}"
    Authorized: "{{ wds_dhcp_authorized | default(omit) }}"
    PSDSCRunAsCredential_username: "{{ domain_admin_user }}"
    PSDSCRunAsCredential_password: "{{ domain_admin_password }}"

- name: Configure boot image
  loop: "{{ wds_boot_images }}"
  ansible.builtin.include_tasks:
    file: boot-image.yml
  loop_control:
    loop_var: _wds_boot_image
