---
- name: Install Windows Deployment Services feature
  ansible.windows.win_feature:
    name:
      - WDS
    include_management_tools: true
    state: present

- name: Initialize WDS
  throttle: 1
  trippsc2.windows.wds_initialize:
    remote_install_path: "{{ wds_path }}"
    standalone: "{{ wds_standalone | default(omit) }}"
    authorized: "{{ wds_dhcp_authorized | default(omit) }}"
    state: initialized
