---
- name: Ensure 'WDSDsc' PowerShell module is installed
  community.windows.win_psmodule:
    name: WDSDsc
    accept_license: true
    state: present

- name: Replace 'WdsBootImage' resource to fix bug
  ansible.windows.win_copy:
    src: JHP_WdsBootImage.psm1
    dest: C:\Program Files\WindowsPowerShell\Modules\WdsDsc\0.11.0\DscResources\JHP_WdsBootImage\

- name: Install Windows Deployment Services feature
  ansible.windows.win_feature:
    name:
      - WDS
    include_management_tools: true
    state: present
