---
galaxy_info:
    author: Jim Tarpley (@trippsc2)
    namespace: trippsc2
    role_name: dhcp_server
    description: This role installs and configures DHCP Server role on Windows Server.
    license: MIT

    min_ansible_version: '2.15'

    platforms:
      - name: Windows
        versions:
          - '2019'
          - '2022'

collections:
  - ansible.windows

dependencies:
  - role: trippsc2.windows.install_psgallery
