---
- name: Gather OS facts
  when:
    - ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - os_family

- name: Validate OS is Windows
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Windows'
    fail_msg: This role is not supported on {{ ansible_os_family }}.
    success_msg: This role is supported on Windows.
