---
dhcp_options:
  - id: 6
    value:
      - "{{ hostvars['dc'].ansible_host }}"
  - id: 15
    value: test.loc

dhcp_scopes:
  - id: '192.168.121.0'
    ip_start: '192.168.121.11'
    ip_end: '192.168.121.250'
    name: '192.168.121.0'
    subnet_mask: '255.255.255.0'
    lease_duration: '00:01:00'
    options:
      - id: 6
        value:
          - "{{ hostvars['dc'].ansible_host }}"
