---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Check if WDS is installed
      check_mode: true
      ansible.windows.win_feature:
        name:
          - WDS
        state: present
      register: _wds_installed

    - name: Verify WDS is installed
      ansible.builtin.assert:
        that:
          - not _wds_installed.changed
        fail_msg: Windows Deployment Services is not installed.
        success_msg: Windows Deployment Services is installed.

    - name: Check if WDS service is running
      check_mode: true
      ansible.windows.win_service:
        name: WDSServer
        state: started
      register: _wds_service_running

    - name: Verify WDS service is running
      ansible.builtin.assert:
        that:
          - not _wds_service_running.changed
        fail_msg: Windows Deployment Services service is not running.
        success_msg: Windows Deployment Services service is running.
